spring:
  application:
    name: spring.cloud.config
  cloud:
    config:
      label: master
      server:
        git:
          uri: http://192.168.92.131/TiSerenity/spring-cloud-config.git
          search-paths: repository
          username: TiSerenity
          password: 12345678
  zipkin:
    base-url: http://localhost:9411
  boot:
    admin:
      client:
        url: http://localhost:8084
server:
  port: 8888
eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/